<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MentionMarginaleNaissance', 'doctrine');

/**
 * BaseMentionMarginaleNaissance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $naissance_id
 * @property string $mention
 * @property date $dateajout
 * @property Naissance $Naissance
 * 
 * @method integer                   getId()           Returns the current record's "id" value
 * @method integer                   getNaissanceId()  Returns the current record's "naissance_id" value
 * @method string                    getMention()      Returns the current record's "mention" value
 * @method date                      getDateajout()    Returns the current record's "dateajout" value
 * @method Naissance                 getNaissance()    Returns the current record's "Naissance" value
 * @method MentionMarginaleNaissance setId()           Sets the current record's "id" value
 * @method MentionMarginaleNaissance setNaissanceId()  Sets the current record's "naissance_id" value
 * @method MentionMarginaleNaissance setMention()      Sets the current record's "mention" value
 * @method MentionMarginaleNaissance setDateajout()    Sets the current record's "dateajout" value
 * @method MentionMarginaleNaissance setNaissance()    Sets the current record's "Naissance" value
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMentionMarginaleNaissance extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mention_marginale_naissance');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('naissance_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('mention', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('dateajout', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Naissance', array(
             'local' => 'naissance_id',
             'foreign' => 'id'));
    }
}