<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ImageRegistreDeces', 'doctrine');

/**
 * BaseImageRegistreDeces
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $deces_id
 * @property string $nomimage
 * @property Deces $Deces
 * 
 * @method integer            getId()       Returns the current record's "id" value
 * @method integer            getDecesId()  Returns the current record's "deces_id" value
 * @method string             getNomimage() Returns the current record's "nomimage" value
 * @method Deces              getDeces()    Returns the current record's "Deces" value
 * @method ImageRegistreDeces setId()       Sets the current record's "id" value
 * @method ImageRegistreDeces setDecesId()  Sets the current record's "deces_id" value
 * @method ImageRegistreDeces setNomimage() Sets the current record's "nomimage" value
 * @method ImageRegistreDeces setDeces()    Sets the current record's "Deces" value
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImageRegistreDeces extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image_registre_deces');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('deces_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('nomimage', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Deces', array(
             'local' => 'deces_id',
             'foreign' => 'id'));
    }
}