<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ImageRegistreNaissance', 'doctrine');

/**
 * BaseImageRegistreNaissance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $naissance_id
 * @property string $nomimage
 * @property Naissance $Naissance
 * 
 * @method integer                getId()           Returns the current record's "id" value
 * @method integer                getNaissanceId()  Returns the current record's "naissance_id" value
 * @method string                 getNomimage()     Returns the current record's "nomimage" value
 * @method Naissance              getNaissance()    Returns the current record's "Naissance" value
 * @method ImageRegistreNaissance setId()           Sets the current record's "id" value
 * @method ImageRegistreNaissance setNaissanceId()  Sets the current record's "naissance_id" value
 * @method ImageRegistreNaissance setNomimage()     Sets the current record's "nomimage" value
 * @method ImageRegistreNaissance setNaissance()    Sets the current record's "Naissance" value
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImageRegistreNaissance extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image_registre_naissance');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('naissance_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('nomimage', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Naissance', array(
             'local' => 'naissance_id',
             'foreign' => 'id'));
    }
}