<?php

/**
 * BaseNaissance_enfant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $naissance_id
 * @property string $nom
 * @property string $prenom
 * @property enum $sexe
 * @property date $dateNaissance
 * @property time $heureNaissance
 * @property string $lieuNaissance
 * @property string $nouveauNom
 * @property string $domicile
 * @property boolean $parentsMaries
 * @property date $dateMariageParents
 * @property string $lieuMariageParents
 * @property Naissance $Naissance
 * 
 * @method integer          getNaissanceId()        Returns the current record's "naissance_id" value
 * @method string           getNom()                Returns the current record's "nom" value
 * @method string           getPrenom()             Returns the current record's "prenom" value
 * @method enum             getSexe()               Returns the current record's "sexe" value
 * @method date             getDateNaissance()      Returns the current record's "dateNaissance" value
 * @method time             getHeureNaissance()     Returns the current record's "heureNaissance" value
 * @method string           getLieuNaissance()      Returns the current record's "lieuNaissance" value
 * @method string           getNouveauNom()         Returns the current record's "nouveauNom" value
 * @method string           getDomicile()           Returns the current record's "domicile" value
 * @method boolean          getParentsMaries()      Returns the current record's "parentsMaries" value
 * @method date             getDateMariageParents() Returns the current record's "dateMariageParents" value
 * @method string           getLieuMariageParents() Returns the current record's "lieuMariageParents" value
 * @method Naissance        getNaissance()          Returns the current record's "Naissance" value
 * @method Naissance_enfant setNaissanceId()        Sets the current record's "naissance_id" value
 * @method Naissance_enfant setNom()                Sets the current record's "nom" value
 * @method Naissance_enfant setPrenom()             Sets the current record's "prenom" value
 * @method Naissance_enfant setSexe()               Sets the current record's "sexe" value
 * @method Naissance_enfant setDateNaissance()      Sets the current record's "dateNaissance" value
 * @method Naissance_enfant setHeureNaissance()     Sets the current record's "heureNaissance" value
 * @method Naissance_enfant setLieuNaissance()      Sets the current record's "lieuNaissance" value
 * @method Naissance_enfant setNouveauNom()         Sets the current record's "nouveauNom" value
 * @method Naissance_enfant setDomicile()           Sets the current record's "domicile" value
 * @method Naissance_enfant setParentsMaries()      Sets the current record's "parentsMaries" value
 * @method Naissance_enfant setDateMariageParents() Sets the current record's "dateMariageParents" value
 * @method Naissance_enfant setLieuMariageParents() Sets the current record's "lieuMariageParents" value
 * @method Naissance_enfant setNaissance()          Sets the current record's "Naissance" value
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNaissance_enfant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('naissance_enfant');
        $this->hasColumn('naissance_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('nom', 'string', 60, array(
             'type' => 'string',
             'charset' => 'utf8',
             'length' => 60,
             ));
        $this->hasColumn('prenom', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'charset' => 'utf8',
             'length' => 60,
             ));
        $this->hasColumn('sexe', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'masculin',
              1 => 'féminin',
             ),
             'default' => 'masculin',
             'notnull' => true,
             'charset' => 'utf8',
             ));
        $this->hasColumn('dateNaissance', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('heureNaissance', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('lieuNaissance', 'string', 4000, array(
             'type' => 'string',
             'notnull' => false,
             'charset' => 'utf8',
             'length' => 4000,
             ));
        $this->hasColumn('nouveauNom', 'string', 150, array(
             'type' => 'string',
             'charset' => 'utf8',
             'length' => 150,
             ));
        $this->hasColumn('domicile', 'string', 4000, array(
             'type' => 'string',
             'notnull' => false,
             'charset' => 'utf8',
             'length' => 4000,
             ));
        $this->hasColumn('parentsMaries', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('dateMariageParents', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('lieuMariageParents', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Naissance', array(
             'local' => 'naissance_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}