<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ImageRegistreMariage', 'doctrine');

/**
 * BaseImageRegistreMariage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mariage_id
 * @property string $nomimage
 * @property Mariage $Mariage
 * 
 * @method integer              getId()         Returns the current record's "id" value
 * @method integer              getMariageId()  Returns the current record's "mariage_id" value
 * @method string               getNomimage()   Returns the current record's "nomimage" value
 * @method Mariage              getMariage()    Returns the current record's "Mariage" value
 * @method ImageRegistreMariage setId()         Sets the current record's "id" value
 * @method ImageRegistreMariage setMariageId()  Sets the current record's "mariage_id" value
 * @method ImageRegistreMariage setNomimage()   Sets the current record's "nomimage" value
 * @method ImageRegistreMariage setMariage()    Sets the current record's "Mariage" value
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImageRegistreMariage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image_registre_mariage');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('mariage_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('nomimage', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mariage', array(
             'local' => 'mariage_id',
             'foreign' => 'id'));
    }
}