<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MentionMarginaleDeces', 'doctrine');

/**
 * BaseMentionMarginaleDeces
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $deces_id
 * @property string $mention
 * @property date $dateajout
 * @property Deces $Deces
 * 
 * @method integer               getId()        Returns the current record's "id" value
 * @method integer               getDecesId()   Returns the current record's "deces_id" value
 * @method string                getMention()   Returns the current record's "mention" value
 * @method date                  getDateajout() Returns the current record's "dateajout" value
 * @method Deces                 getDeces()     Returns the current record's "Deces" value
 * @method MentionMarginaleDeces setId()        Sets the current record's "id" value
 * @method MentionMarginaleDeces setDecesId()   Sets the current record's "deces_id" value
 * @method MentionMarginaleDeces setMention()   Sets the current record's "mention" value
 * @method MentionMarginaleDeces setDateajout() Sets the current record's "dateajout" value
 * @method MentionMarginaleDeces setDeces()     Sets the current record's "Deces" value
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMentionMarginaleDeces extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mention_marginale_deces');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('deces_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('mention', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('dateajout', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Deces', array(
             'local' => 'deces_id',
             'foreign' => 'id'));
    }
}