<?php

/**
 * BaseMention_marginaleNaissance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $naissance_id
 * @property string $mention
 * @property date $dateAjout
 * @property Naissance $Naissance
 * 
 * @method integer                    getNaissanceId()  Returns the current record's "naissance_id" value
 * @method string                     getMention()      Returns the current record's "mention" value
 * @method date                       getDateAjout()    Returns the current record's "dateAjout" value
 * @method Naissance                  getNaissance()    Returns the current record's "Naissance" value
 * @method Mention_marginaleNaissance setNaissanceId()  Sets the current record's "naissance_id" value
 * @method Mention_marginaleNaissance setMention()      Sets the current record's "mention" value
 * @method Mention_marginaleNaissance setDateAjout()    Sets the current record's "dateAjout" value
 * @method Mention_marginaleNaissance setNaissance()    Sets the current record's "Naissance" value
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMention_marginaleNaissance extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mention_marginale_naissance');
        $this->hasColumn('naissance_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mention', 'string', 4000, array(
             'type' => 'string',
             'charset' => 'utf8',
             'length' => 4000,
             ));
        $this->hasColumn('dateAjout', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Naissance', array(
             'local' => 'naissance_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}