<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Notaires', 'doctrine');

/**
 * BaseNotaires
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom
 * @property string $prenom
 * @property string $adresse
 * 
 * @method integer  getId()      Returns the current record's "id" value
 * @method string   getNom()     Returns the current record's "nom" value
 * @method string   getPrenom()  Returns the current record's "prenom" value
 * @method string   getAdresse() Returns the current record's "adresse" value
 * @method Notaires setId()      Sets the current record's "id" value
 * @method Notaires setNom()     Sets the current record's "nom" value
 * @method Notaires setPrenom()  Sets the current record's "prenom" value
 * @method Notaires setAdresse() Sets the current record's "adresse" value
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotaires extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notaires');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('nom', 'string', 90, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 90,
             ));
        $this->hasColumn('prenom', 'string', 90, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 90,
             ));
        $this->hasColumn('adresse', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}