<?php

/**
 * BaseImage_registreDeces
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $deces_id
 * @property string $nomImage
 * @property Deces $Deces
 * 
 * @method integer             getDecesId()  Returns the current record's "deces_id" value
 * @method string              getNomImage() Returns the current record's "nomImage" value
 * @method Deces               getDeces()    Returns the current record's "Deces" value
 * @method Image_registreDeces setDecesId()  Sets the current record's "deces_id" value
 * @method Image_registreDeces setNomImage() Sets the current record's "nomImage" value
 * @method Image_registreDeces setDeces()    Sets the current record's "Deces" value
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImage_registreDeces extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image_registre_deces');
        $this->hasColumn('deces_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nomImage', 'string', 4000, array(
             'type' => 'string',
             'charset' => 'utf8',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Deces', array(
             'local' => 'deces_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}