<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Naissance', 'doctrine');

/**
 * BaseNaissance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $numeroacte
 * @property integer $numeroordre
 * @property string $typeacte
 * @property date $dateacte
 * @property time $heureacte
 * @property date $datereconnaissance
 * @property string $lieureconnaissance
 * @property Doctrine_Collection $ImageRegistreNaissance
 * @property Doctrine_Collection $MentionMarginaleNaissance
 * @property Doctrine_Collection $NaissanceActeur
 * @property Doctrine_Collection $NaissanceEnfant
 * 
 * @method integer             getId()                        Returns the current record's "id" value
 * @method integer             getNumeroacte()                Returns the current record's "numeroacte" value
 * @method integer             getNumeroordre()               Returns the current record's "numeroordre" value
 * @method string              getTypeacte()                  Returns the current record's "typeacte" value
 * @method date                getDateacte()                  Returns the current record's "dateacte" value
 * @method time                getHeureacte()                 Returns the current record's "heureacte" value
 * @method date                getDatereconnaissance()        Returns the current record's "datereconnaissance" value
 * @method string              getLieureconnaissance()        Returns the current record's "lieureconnaissance" value
 * @method Doctrine_Collection getImageRegistreNaissance()    Returns the current record's "ImageRegistreNaissance" collection
 * @method Doctrine_Collection getMentionMarginaleNaissance() Returns the current record's "MentionMarginaleNaissance" collection
 * @method Doctrine_Collection getNaissanceActeur()           Returns the current record's "NaissanceActeur" collection
 * @method Doctrine_Collection getNaissanceEnfant()           Returns the current record's "NaissanceEnfant" collection
 * @method Naissance           setId()                        Sets the current record's "id" value
 * @method Naissance           setNumeroacte()                Sets the current record's "numeroacte" value
 * @method Naissance           setNumeroordre()               Sets the current record's "numeroordre" value
 * @method Naissance           setTypeacte()                  Sets the current record's "typeacte" value
 * @method Naissance           setDateacte()                  Sets the current record's "dateacte" value
 * @method Naissance           setHeureacte()                 Sets the current record's "heureacte" value
 * @method Naissance           setDatereconnaissance()        Sets the current record's "datereconnaissance" value
 * @method Naissance           setLieureconnaissance()        Sets the current record's "lieureconnaissance" value
 * @method Naissance           setImageRegistreNaissance()    Sets the current record's "ImageRegistreNaissance" collection
 * @method Naissance           setMentionMarginaleNaissance() Sets the current record's "MentionMarginaleNaissance" collection
 * @method Naissance           setNaissanceActeur()           Sets the current record's "NaissanceActeur" collection
 * @method Naissance           setNaissanceEnfant()           Sets the current record's "NaissanceEnfant" collection
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNaissance extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('naissance');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('numeroacte', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('numeroordre', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('typeacte', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'naissance',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('dateacte', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('heureacte', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('datereconnaissance', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('lieureconnaissance', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ImageRegistreNaissance', array(
             'local' => 'id',
             'foreign' => 'naissance_id'));

        $this->hasMany('MentionMarginaleNaissance', array(
             'local' => 'id',
             'foreign' => 'naissance_id'));

        $this->hasMany('NaissanceActeur', array(
             'local' => 'id',
             'foreign' => 'naissance_id'));

        $this->hasMany('NaissanceEnfant', array(
             'local' => 'id',
             'foreign' => 'naissance_id'));
    }
}