<?php

/**
 * BaseMention_marginaleMariage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mariage_id
 * @property string $mention
 * @property date $dateAjout
 * @property Mariage $Mariage
 * 
 * @method integer                  getMariageId()  Returns the current record's "mariage_id" value
 * @method string                   getMention()    Returns the current record's "mention" value
 * @method date                     getDateAjout()  Returns the current record's "dateAjout" value
 * @method Mariage                  getMariage()    Returns the current record's "Mariage" value
 * @method Mention_marginaleMariage setMariageId()  Sets the current record's "mariage_id" value
 * @method Mention_marginaleMariage setMention()    Sets the current record's "mention" value
 * @method Mention_marginaleMariage setDateAjout()  Sets the current record's "dateAjout" value
 * @method Mention_marginaleMariage setMariage()    Sets the current record's "Mariage" value
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMention_marginaleMariage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mention_marginale_mariage');
        $this->hasColumn('mariage_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mention', 'string', 4000, array(
             'type' => 'string',
             'charset' => 'utf8',
             'length' => 4000,
             ));
        $this->hasColumn('dateAjout', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mariage', array(
             'local' => 'mariage_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}