<?php

/**
 * BaseImage_registreMariage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mariage_id
 * @property string $nomImage
 * @property Mariage $Mariage
 * 
 * @method integer               getMariageId()  Returns the current record's "mariage_id" value
 * @method string                getNomImage()   Returns the current record's "nomImage" value
 * @method Mariage               getMariage()    Returns the current record's "Mariage" value
 * @method Image_registreMariage setMariageId()  Sets the current record's "mariage_id" value
 * @method Image_registreMariage setNomImage()   Sets the current record's "nomImage" value
 * @method Image_registreMariage setMariage()    Sets the current record's "Mariage" value
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImage_registreMariage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image_registre_mariage');
        $this->hasColumn('mariage_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nomImage', 'string', 4000, array(
             'type' => 'string',
             'charset' => 'utf8',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mariage', array(
             'local' => 'mariage_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}