<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MentionMarginaleMariage', 'doctrine');

/**
 * BaseMentionMarginaleMariage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mariage_id
 * @property string $mention
 * @property date $dateajout
 * @property Mariage $Mariage
 * 
 * @method integer                 getId()         Returns the current record's "id" value
 * @method integer                 getMariageId()  Returns the current record's "mariage_id" value
 * @method string                  getMention()    Returns the current record's "mention" value
 * @method date                    getDateajout()  Returns the current record's "dateajout" value
 * @method Mariage                 getMariage()    Returns the current record's "Mariage" value
 * @method MentionMarginaleMariage setId()         Sets the current record's "id" value
 * @method MentionMarginaleMariage setMariageId()  Sets the current record's "mariage_id" value
 * @method MentionMarginaleMariage setMention()    Sets the current record's "mention" value
 * @method MentionMarginaleMariage setDateajout()  Sets the current record's "dateajout" value
 * @method MentionMarginaleMariage setMariage()    Sets the current record's "Mariage" value
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMentionMarginaleMariage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mention_marginale_mariage');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('mariage_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('mention', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('dateajout', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mariage', array(
             'local' => 'mariage_id',
             'foreign' => 'id'));
    }
}