<?php

/**
 * BaseImage_registreNaissance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $naissance_id
 * @property string $nomImage
 * @property Naissance $Naissance
 * 
 * @method integer                 getNaissanceId()  Returns the current record's "naissance_id" value
 * @method string                  getNomImage()     Returns the current record's "nomImage" value
 * @method Naissance               getNaissance()    Returns the current record's "Naissance" value
 * @method Image_registreNaissance setNaissanceId()  Sets the current record's "naissance_id" value
 * @method Image_registreNaissance setNomImage()     Sets the current record's "nomImage" value
 * @method Image_registreNaissance setNaissance()    Sets the current record's "Naissance" value
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImage_registreNaissance extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image_registre_naissance');
        $this->hasColumn('naissance_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nomImage', 'string', 4000, array(
             'type' => 'string',
             'charset' => 'utf8',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Naissance', array(
             'local' => 'naissance_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}