notaires:
  class: sfDoctrineRouteCollection
  options:
    model:                Notaires
    module:               notaires
    prefix_path:          /notaires
    column:               id
    with_wildcard_routes: true

officiers:
  class: sfDoctrineRouteCollection
  options:
    model:                Officiers
    module:               officiers
    prefix_path:          /officiers
    column:               id
    with_wildcard_routes: true

ville_france:
  class: sfDoctrineRouteCollection
  options:
    model:                ville_france
    module:               ville_france
    prefix_path:          /ville_france
    column:               id
    with_wildcard_routes: true

utilisateur:
  class: sfDoctrineRouteCollection
  options:
    model:                utilisateur
    module:               utilisateur
    prefix_path:          /utilisateur
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: main, action: index }

Compte_User:
  url:  /admin/gestion/utilisateur
  param: { module: utilisateur, action: index }

Villes_france:
  url:  /admin/gestion/villes_france
  param: { module: ville_france, action: index }

Officiers:
  url:  /admin/gestion/officiers
  param: { module: officiers, action: index }

Notaires:
  url:  /admin/gestion/notaires
  param: { module: notaires, action: index }

 
# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }
#
#default:
#  url:   /:module/:action/*