<?php

/**
 * Deces
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    etatCivil
 * @subpackage model
 * @author     Boyer jimmy
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Deces extends BaseDeces
{
     /**
     * Cette fonction récupère l'année de l'acte passé en paramètre
     *
     * @author    FLAMENT Guillaume
     * @param     int $id
     */
    public static function getAnneeActe($id){

      $res = Doctrine_Query::create()       //récupère un array avec les résultats de type décès (ici l'array ne comporte qu'un décès)
            ->select('dateacte')            //car on met l'id dans le where
            ->from('Deces d')
            ->where('d.id = ?', $id)
            ->execute();

       
        $date = $res->get(0);
        
        return date('Y',strtotime(($date->get('dateActe'))));   // renvoie l'année de la date convertie en int pour appeler la fonction date()
    }

}
