<?php

/**
 * Image_registreDecesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Image_registreDecesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Image_registreDecesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Image_registreDeces');
    }
}