<?php

/**
 * ImageRegistreNaissanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImageRegistreNaissanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImageRegistreNaissanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImageRegistreNaissance');
    }
}