<?php

/**
 * Image_registreMariageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Image_registreMariageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Image_registreMariageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Image_registreMariage');
    }
}