<?php

/**
 * ImageRegistreDecesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImageRegistreDecesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImageRegistreDecesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImageRegistreDeces');
    }
}