<?php

/**
 * ImageRegistreMariageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImageRegistreMariageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImageRegistreMariageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImageRegistreMariage');
    }
}