<?php

/**
 * Image_registreMariage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    etatCivil
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Image_registreMariage extends BaseImage_registreMariage
{
    public function generateNomImageFilename(sfValidatedFile $file) {
        return Doctrine_Inflector::urlize(substr($file->getOriginalName(),0,-4));
    }
}