<?php

/**
 * ImageRegistreMariage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ImageRegistreMariage extends BaseImageRegistreMariage
{
}
