<?php

/**
 * Mariage_contact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    etatCivil
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Mariage_contact extends BaseMariage_contact
{
    public function getActeur_id()
    {
       $acteur = Doctrine_Query::create()
            ->from('Mariage_acteur act')
                ->where("act.mariage_id = ?", $this->getMariageId() )
                ->andWhere('act.typeActeur= ?', $this->getEnRelationA())
                ->execute();

       return $acteur->getFirst()->getId();
    }

}
