<?php

/**
 * MariageActeurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MariageActeurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MariageActeurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MariageActeur');
    }
}