<?php

/**
 * MariageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MariageTable extends Doctrine_Table
{
  //-----------------------------------------------------------
    // Concerne les Acteurs
  public function recupereActeurs(Doctrine_Query $q)
  {
    return $this->addActeursQuery($q)->fetchOne();
  }

  public function getActeurs(Doctrine_Query $q = null)
  {
    return $this->addActeursQuery($q)->execute();
  }

  public function compteLesActeurs(Doctrine_Query $q = null)
  {
    return $this->addActeursQuery($q)->count();
  }

  public function addActeursQuery(Doctrine_Query $q = null)
  {
    if (is_null($q))
    {
      $q = Doctrine_Query::create()
        ->from('Mariage_acteur act');
    }
    return $q;
  }
    //
  //-----------------------------------------------------------

  //-----------------------------------------------------------
    // Concernant les temoins :
  public function recupereTemoins(Doctrine_Query $q)
  {
    return $this->addTemoinsQuery($q)->fetchOne();
  }

  public function getTemoins(Doctrine_Query $q = null)
  {
    return $this->addTemoinsQuery($q)->execute();
  }

  public function compteLesTemoins(Doctrine_Query $q = null)
  {
    return $this->addTemoinsQuery($q)->count();
  }

  public function addTemoinsQuery(Doctrine_Query $q = null)
  {
    if (is_null($q))
    {
      $q = Doctrine_Query::create()
        ->from('Mariage_acteur act');
    }
    return $q;
  }


}