<?php

/**
 * MariageContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MariageContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MariageContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MariageContact');
    }
}