<?php

/**
 * Mariage_acteur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    etatCivil
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Mariage_acteur extends BaseMariage_acteur
{
        /*
     * Getter de la Table Mariage permettant de recuperer les
     * Acteur/contact en relation au bon acte
     */
    public function getPere()
    {
        $pereC = Doctrine_Query::create()
            ->from('Mariage_contact con')
                ->where("con.mariage_id = ?", $this->getMariageId() )
                ->andWhere('con.enrelationa = ?', $this->getTypeActeur())
                ->andWhere('con.typeContact = ?', "père")
                ->execute();

        $pere = $pereC->getFirst();

        if ($pere != null)
            return $pere;
        else
            return null;

    }

     public function getMere()
    {
        $mereC = Doctrine_Query::create()
            ->from('Mariage_contact con')
                ->where("con.mariage_id = ?", $this->getMariageId() )
                ->andWhere('con.enrelationa = ?', $this->getTypeActeur())
                ->andWhere('con.typeContact = ?', "mère")
                ->execute();

        $mere = $mereC->getFirst();

        if ($mere != null)
            return $mere;
        else
            return null;
    }

}
