<?php

/**
 * Mariage_contactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mariage_contactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mariage_contactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mariage_contact');
    }
}