<?php

/**
 * MentionMarginaleNaissanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MentionMarginaleNaissanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MentionMarginaleNaissanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MentionMarginaleNaissance');
    }
}