<?php

/**
 * MentionMarginaleDecesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MentionMarginaleDecesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MentionMarginaleDecesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MentionMarginaleDeces');
    }
}