<?php

/**
 * Mention_marginaleNaissanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mention_marginaleNaissanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mention_marginaleNaissanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mention_marginaleNaissance');
    }
}