<?php

/**
 * NaissanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NaissanceTable extends Doctrine_Table
{
  //-----------------------------------------------------------
    // Concernant les contacts :
  public function recupereContact(Doctrine_Query $q)
  {
    return $this->addContactQuery($q)->fetchOne();
  }

  public function getContact(Doctrine_Query $q = null)
  {
    return $this->addContactQuery($q)->execute();
  }

  public function compteLesContacts(Doctrine_Query $q = null)
  {
    return $this->addContactQuery($q)->count();
  }

  public function addContactQuery(Doctrine_Query $q = null)
  {
    if (is_null($q))
    {
      $q = Doctrine_Query::create()
        ->from('Naissance_acteur act');
    }
    return $q;
  }
}