<?php

/**
 * Naissance_acteurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Naissance_acteurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Naissance_acteurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Naissance_acteur');
    }
}