<?php

/**
 * Notaires
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Notaires extends BaseNotaires
{
    public static function getNPNotaire($a)
    {
        $r = Doctrine_core::getTable("notaires")->find($a);
        if($r != null) {
            return ("Maitre ".$r->getPrenom()." ".$r->getNom());
        } else {
            return $a;
        }
    }

    public static function getNomNotaire($a)
    {
        $r = Doctrine_core::getTable("notaires")->find($a);
        if($r != null) {
            return ($r->getNom());
        } else {
            return $a;
        }
    }

    public static function getPrenomNotaire($a)
    {
        $r = Doctrine_core::getTable("notaires")->find($a);
        if($r != null) {
            return ($r->getPrenom());
        } else {
            return $a;
        }
    }

    public static function getAdresseNotaire($a)
    {
        $r = Doctrine_core::getTable("notaires")->find($a);
        if($r != null) {
            return ($r->getAdresse());
        } else {
            return $a;
        }
    }
}
