<?php

/**
 * OfficiersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OfficiersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OfficiersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Officiers');
    }
}