<?php

/**
 * Ville_france
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    etatcivil
 * @subpackage model
 * @author     Boyer Jimmy
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Ville_france extends BaseVille_france
{
    public static function getVilleCP($a)
    {
        $r = Doctrine_core::getTable("Ville_france")->find($a);
        if($r != null) {
            return ($r->getVille()." (".$r->getCP().")");
        } else {
            return $a;
        }
    }

    public static function getVilleDepartement($a)
    {
        $r = Doctrine_core::getTable("Ville_france")->find($a);
        if($r != null) {
            return ($r->getVille()." (".$r->getDepartement().")");
        } else {
            return $a;
        }
    }
}
