<?php

/**
 * VilleFranceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleFranceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleFranceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleFrance');
    }
}