<?php

/**
 * Ville_franceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Ville_franceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Ville_franceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ville_france');
    }


}