<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/04 15:04:52

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=etatCivil',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
