<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/04 15:04:52
sfConfig::add(array(
  'app_sf_tiny_doc_plugin_zip_method' => 'shell',
  'app_sf_tiny_doc_plugin_zip_bin' => 'zip',
  'app_sf_tiny_doc_plugin_unzip_bin' => 'unzip',
  'app_sf_tiny_doc_plugin_process_dir' => '/home/romain/mairie2013-2014/etatCivil/web/tmp',
));
