<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/01/29 11:30:16
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'user',
        1 => 'admin',
      ),
    ),
  ),
);
