<?php
// auto-generated by sfViewConfigHandler
// date: 2014/01/29 11:30:16
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'popUpDocumentsSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'popUpDocumentsSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'layout_popUp' ? false : 'layout_popUp'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('jquery-ui-1.8.11.custom.css', '', array ());
  $response->addStylesheet('admin.css', '', array ());
  $response->addJavascript('/js/jquery/jquery-1.3.js', '', array ());
  $response->addJavascript('jquery-ui-1.8.11.custom.min.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('jquery-ui-1.8.11.custom.css', '', array ());
  $response->addStylesheet('admin.css', '', array ());
  $response->addJavascript('/js/jquery/jquery-1.3.js', '', array ());
  $response->addJavascript('jquery-ui-1.8.11.custom.min.js', '', array ());
}

