<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('mariage_acteur', 'sexe');
    }

    public function down()
    {
        $this->addColumn('mariage_acteur', 'sexe', 'enum', '', array(
             'values' => 
             array(
              0 => 'h',
              1 => 'f',
             ),
             'default' => 'époux',
             'notnull' => 'h',
             'charset' => 'utf8',
             ));
    }
}