<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('mariage_acteur', 'sexe', 'enum', '', array(
             'values' => 
             array(
              0 => 'h',
              1 => 'f',
             ),
             'default' => 'époux',
             'notnull' => 'h',
             'charset' => 'utf8',
             ));
        $this->changeColumn('naissance_enfant', 'datemariageparents', 'date', '25', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('mariage_acteur', 'sexe');
    }
}