<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('mariage_contact', 'enrelationa', 'enum', '', array(
             'values' => 
             array(
              0 => 'conjoint1',
              1 => 'conjoint2',
             ),
             'default' => 'époux',
             'notnull' => '1',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {

    }
}