<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('image_registre_deces');
        $this->dropTable('image_registre_mariage');
        $this->dropTable('image_registre_naissance');
        $this->dropTable('mariage_acteur');
        $this->dropTable('mariage_contact');
        $this->dropTable('mention_marginale_deces');
        $this->dropTable('mention_marginale_mariage');
        $this->dropTable('mention_marginale_naissance');
        $this->dropTable('naissance_acteur');
        $this->dropTable('naissance_enfant');
        $this->dropTable('ville_france');
    }

    public function down()
    {
        $this->createTable('image_registre_deces', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'deces_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'nomimage' => 
             array(
              'type' => 'string',
              'charset' => 'utf8',
              'length' => '4000',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('image_registre_mariage', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'mariage_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'nomimage' => 
             array(
              'type' => 'string',
              'charset' => 'utf8',
              'length' => '4000',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('image_registre_naissance', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'naissance_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'nomimage' => 
             array(
              'type' => 'string',
              'charset' => 'utf8',
              'length' => '4000',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('mariage_acteur', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'mariage_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'nom' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '60',
             ),
             'prenom' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '60',
             ),
             'sexe' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'homme',
              1 => 'femme',
              ),
              'default' => 'homme',
              'notnull' => 'homme',
              'charset' => 'utf8',
              'length' => '',
             ),
             'typeacteur' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'conjoint1',
              1 => 'conjoint2',
              ),
              'default' => 'conjoint1',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '',
             ),
             'datenaissance' => 
             array(
              'type' => 'date',
              'notnull' => '1',
              'length' => '25',
             ),
             'lieunaissance' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '4000',
             ),
             'domicile' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '4000',
             ),
             'residence' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'charset' => 'utf8',
              'length' => '4000',
             ),
             'profession' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '70',
             ),
             'etatanterieurmariage' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'célibataire',
              1 => 'veuf(ve)',
              2 => 'divorcé(e)',
              ),
              'default' => 'célibataire',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '',
             ),
             'nomprenomprecconjoint' => 
             array(
              'type' => 'string',
              'charset' => 'utf8',
              'length' => '90',
             ),
             'nomapresmariage' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'charset' => 'utf8',
              'length' => '60',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('mariage_contact', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'mariage_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'nom' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '60',
             ),
             'prenom' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '60',
             ),
             'sexe' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'masculin',
              1 => 'féminin',
              ),
              'default' => 'masculin',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '',
             ),
             'typecontact' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'témoin',
              1 => 'père',
              2 => 'mère',
              ),
              'default' => 'témoin',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '',
             ),
             'enrelationa' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'conjoint1',
              1 => 'conjoint2',
              ),
              'default' => 'époux',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '',
             ),
             'info' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => '',
              1 => 'décédé(e)',
              ),
              'default' => ', notnull: false',
              'charset' => 'UTF8',
              'length' => '',
             ),
             'age' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'domicile' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'charset' => 'utf8',
              'length' => '4000',
             ),
             'profession' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'charset' => 'utf8',
              'length' => '70',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('mention_marginale_deces', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'deces_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'mention' => 
             array(
              'type' => 'string',
              'charset' => 'utf8',
              'length' => '4000',
             ),
             'dateajout' => 
             array(
              'type' => 'date',
              'notnull' => '1',
              'length' => '25',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('mention_marginale_mariage', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'mariage_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'mention' => 
             array(
              'type' => 'string',
              'charset' => 'utf8',
              'length' => '4000',
             ),
             'dateajout' => 
             array(
              'type' => 'date',
              'notnull' => '1',
              'length' => '25',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('mention_marginale_naissance', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'naissance_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'mention' => 
             array(
              'type' => 'string',
              'charset' => 'utf8',
              'length' => '4000',
             ),
             'dateajout' => 
             array(
              'type' => 'date',
              'notnull' => '1',
              'length' => '25',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('naissance_acteur', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'naissance_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'nom' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '60',
             ),
             'prenom' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '60',
             ),
             'sexe' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'masculin',
              1 => 'féminin',
              ),
              'default' => 'masculin',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '',
             ),
             'age' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'length' => '8',
             ),
             'datenaissance' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             'lieunaissance' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'charset' => 'utf8',
              'length' => '4000',
             ),
             'profession' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'charset' => 'utf8',
              'length' => '70',
             ),
             'domicile' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'charset' => 'utf8',
              'length' => '4000',
             ),
             'estdeclarant' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '0',
              'length' => '25',
             ),
             'typeacteur' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'père',
              1 => 'mère',
              2 => 'autre préciser...',
              ),
              'default' => 'père',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '',
             ),
             'typeautres' => 
             array(
              'type' => 'string',
              'charset' => 'utf8',
              'length' => '70',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('naissance_enfant', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'naissance_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'unique' => '1',
              'length' => '8',
             ),
             'nom' => 
             array(
              'type' => 'string',
              'charset' => 'utf8',
              'length' => '60',
             ),
             'prenom' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '60',
             ),
             'sexe' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'masculin',
              1 => 'féminin',
              ),
              'default' => 'masculin',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '',
             ),
             'datenaissance' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             'heurenaissance' => 
             array(
              'type' => 'time',
              'length' => '25',
             ),
             'lieunaissance' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'charset' => 'utf8',
              'length' => '4000',
             ),
             'nouveaunom' => 
             array(
              'type' => 'string',
              'charset' => 'utf8',
              'length' => '150',
             ),
             'domicile' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'charset' => 'utf8',
              'length' => '4000',
             ),
             'parentsmaries' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '1',
              'length' => '25',
             ),
             'datemariageparents' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             'lieumariageparents' => 
             array(
              'type' => 'string',
              'length' => '4000',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('ville_france', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'cp' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '5',
             ),
             'ville' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '50',
             ),
             'region' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '40',
             ),
             'departement' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'charset' => 'utf8',
              'length' => '60',
             ),
             'pays' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'charset' => 'utf8',
              'length' => '40',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }
}