<?php

/**
 * MariageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MariageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MariageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mariage');
    }
}