<?php

/**
 * Mention_marginaleMariageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mention_marginaleMariageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mention_marginaleMariageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mention_marginaleMariage');
    }
}