<?php

/**
 * Mention_marginaleDecesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mention_marginaleDecesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mention_marginaleDecesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mention_marginaleDeces');
    }
}