<?php

/**
 * NaissanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NaissanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NaissanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Naissance');
    }
}