<?php

/**
 * Naissance_enfantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Naissance_enfantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Naissance_enfantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Naissance_enfant');
    }
}